qrep/bastama/urls.py
from django.urls import path
from .views import *

app_name = 'bastama'

urlpatterns = [
    path('', index, name='home'),
    path('category/<str:cat_name>/', category_products, name='category_products'),
    path('product/<slug:slug>/', product_detail, name='product_detail'),
    path('search/', search, name='search'),
    path('favorite/', favorite_products, name='favorite'),
    path('basket/', basket, name='basket'),

    path('lookbook/', lookbook, name='lookbook'),
    path('test/', test, name='test'),

    path('update_favs/<slug:slug>/', click_like, name='click_like'),
]

qrep/bastama/models.py
from django.db import models
from django.contrib.auth.models import User  # Importing User model from auth app


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)

    def __str__(self):
        return self.user if self.user else self.name


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'


class Product(models.Model):
    slug = models.SlugField(unique=True, max_length=200)
    name = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    first_photo = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Favors(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=True)
    transaction = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.pk)

    @property
    def get_basket_amount(self):
        basket_order_items = self.orderitem_set.all()
        return sum([item.quantity * item.product.price for item in basket_order_items])

    @property
    def get_basket_total(self):
        basket_order_items = self.orderitem_set.all()
        return sum([item.quantity for item in basket_order_items])


class Color(models.Model):
    name = models.CharField(max_length=100)
    color_code = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.name


class Size(models.Model):
    name = models.CharField(max_length=100)
    size_code = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.size_code


class ProductAttribute(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    color = models.ForeignKey(Color, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.product.name


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE, null=True, blank=True)
    product_attr = models.ForeignKey(ProductAttribute, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=255, null=True)
    city = models.CharField(max_length=255, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

qrep/bastama/forms.py
from django import forms

from .models import *


# class OrderItemForm(forms.ModelForm):
#     class Meta:
#         model = OrderItem
#         fields = {
#             'quantity',
#             'size'
#         }

qrep/bastama/views.py
from django.shortcuts import redirect
from django.core.mail import send_mail
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from .models import *
from .forms import *
from .utils import *

app_name = 'bastama'


def index(request):

    if request.method == "POST":
        message_email = request.POST['message-email']
        message_name = request.POST['message-name']
        message = request.POST['message']

        send_mail(
            'message from ' + message_name + ',' + message_email,
            message,
            message_email,
            ['200103223@stu.sdu.edu.kz'],
        )
        return redirect("bastama:home")
    else:
        return render(request, 'bastama/index.html', {'title': 'Qazaq Republic'})

    if request.method == "GET":
        message_email = request.GET['message-ems']

        send_mail(
            'subscription from ' + message_ems,
            ['200103223@stu.sdu.edu.kz'],
        )
        return redirect("bastama:home")

    else:
        return render(request, 'bastama/index.html', {'title': 'Qazaq Republic'})


def category_products(request, cat_name):
    context = dict()
    context['title'] = cat_name.capitalize()

    products_from_subcategory = SIDEBAR_SUBCATEGORY_PRODUCTS[cat_name]
    template_url = get_template_url_for_category(cat_name)

    for product_tuple in products_from_subcategory:
        context_key = product_tuple[0]
        value_to_filter = product_tuple[1]
        context[context_key] = Product.objects.filter(category__name=value_to_filter)

    return render(request, template_url, context)


def product_detail(request, slug):
    context = dict()
    context['data'] = Product.objects.get(slug=slug)
    context['sizes'] = Size.objects.all()
    context['title'] = context['data'].name

    return render(request, 'bastama/views/product.html', context)


def basket(request):
    basket_data = get_basket_data(request)  # Getting all products from basket
    print(basket_data)
    return render(request, 'bastama/basket.html')


@login_required(login_url='/accounts/login/')
def favorite_products(request):
    context = dict()
    context['title'] = 'Favorite Products'

    customer, _ = Customer.objects.get_or_create(user=request.user)
    context['favorites'] = Favors.objects.filter(customer=customer)

    return render(request, 'bastama/views/favorite_products.html', context)


def search(request):
    context = dict()
    context['title'] = 'Search'

    if request.method == 'POST':
        context['products'] = Product.objects.filter(name__contains=request.POST['search'],
                                                     category__name__contains=request.POST['search'])

    return render(request, 'bastama/search.html', context)


def lookbook(request):
    return render(request, 'bastama/lookbook.html')


def click_like(request, slug):
    customer, _ = Customer.objects.get_or_create(user=request.user)
    favorite_product = Product.objects.get(slug=slug)

    favorite, is_fav = is_favorite_of_customer(customer, favorite_product)

    if is_fav:
        favorite.delete()
    else:
        Favors.objects.create(customer=customer, product=favorite_product)

    return redirect('bastama:product_detail', slug=slug)


def test(request):
    context = {'title': 'test'}

    set_product_to_basket(request, context['form'])
    return render(request, 'bastama/components/test.html', context)

qrep/bastama/templates/bastama/components/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Podkova:wght@800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Spartan:wght@500&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://unpkg.com/babel-standalone/babel.min.js"></script>
    <script src="https://unpkg.com/vue/dist/vue.min.js"></script>
    <script src="https://unpkg.com/vue-material@beta"></script>

    <link rel="stylesheet" href="{% static 'bastama/css/style.css' %}">
    {% block style %}
    {% endblock  %}
    <title>{{ title }}</title>
    <script type="text/javascript">
        let user = '{{ request.user }}'

        function get_cookie(name) {
            const cookieArr = document.cookie.split(';')

            for (let i = 0; i < cookieArr.length; i++) {
                const cookiePair = cookieArr[i].split('=')

                if (cookiePair[0] === name) {
                    return decodeURIComponent(cookiePair[1])
                }
            }
            return null
        }

        let cart = JSON.parse(get_cookie('cart'))

        if (cart == undefined) {
            cart = {}
            console.log('cart was added')
            document.cookie = 'cart=' + JSON.stringify(cart) + ';domain=;path=/'
        }
        console.log('cart', cart)

    </script>
</head>
<body>

{% include './header.html' %}

{% block content %}
{% endblock  %}

{% include './footer.html' %}

<script type="text/javascript" src="{% static 'bastama/js/script.js' %}"></script>
</body>
</html>

qrep/bastama/templates/bastama/components/test.html
{% load static %}

{# Configuring the style path #}
{% block style %}
    <link rel="stylesheet" href="{% static 'bastama/css/fix.css' %}">
    <link rel="stylesheet" href="{% static 'bastama/css/style.css' %}">
{% endblock style %}

{% block content %}
    <main>
        <div class="content">
            <h1>Order page</h1>
            <form method="post">
                {% csrf_token %}
                {{ form }}
                <button type="submit" class="button">Save</button>
            </form>
        </div>
    </main>
    <script src="{% static 'bastama/js/basket.js' %}"></script>
{% endblock content %}

qrep/bastama/templates/bastama/gift.html
{% extends './components/base.html' %}
{% load static %}

{# Configuring the style path #}
{% block style %}
    <link rel="stylesheet" href="{% static 'bastama/css/gift.css' %}">
{% endblock style %}

{# Block of Content starting right here #}
{% block content %}

<div class="sidebar" id="sidebar">
    <ul class="sidebar__menu">
        <li class="menu__item">
            <a href="#jeide" class="menu__link">GiftBox</a>
        </li>

        <li class="menu__item">
            <a href="{% url 'bastama:category_products' 'jeans' %}" class="menu__link"><span style="color: yellow;">Jeans</span> </a>
        </li>
        <li class="menu__item">
            <a href="{% url 'bastama:category_products' 'qosymsha' %}" class="menu__link"><span style="color: yellow;">Qosymsha</span> </a>
        </li>
        <li class="menu__item">
            <a href="{% url 'bastama:category_products' 'jeide' %}" class="menu__link"><span style="color: yellow;">Jeide</span> </a>
        </li>
    </ul>
</div>
<!-- --------------------------------------------------------------------------------------- -->
<main>
    <div class="content">
        <div class="nameblock1" id="jeide">gfvgrd</div>
        <div class="nameblock" id="jeide">#GiftBox</div>
        <div class="content_blocks">
            {% for prod in gifts %}
            <div class="cardblock">
                {% if prod.first_photo %}
                    <div class="imageblock15" style="background: url({{ prod.first_photo.url }})"></div>
                {% else %}
                    <div class="imageblock15">No photo</div>
                {% endif %}
                <div class="nameelement">{{ prod.name }}</div>
                <div class="coastel">{{ prod.price | floatformat }} KZT</div>
                <a class="button" href="{% url 'bastama:product_detail' prod.slug %}">Shop Now</a>
            </div>
            {% endfor %}
        </div>
    </div>

</main>

<!-- ------------------------------------------------------------------------------------ -->

{% endblock content %}

qrep/bastama/templates/bastama/jeans.html
{% extends './components/base.html' %}
{% load static %}

{# Configuring the style path #}
{% block style %}
    <link rel="stylesheet" href="{% static 'bastama/css/jeans.css' %}">
{% endblock style %}

{# Block Content starting here #}
{% block content %}
<div class="sidebar" id="sidebar">
    <ul class="sidebar__menu">
        <li class="menu__item">
            <a href="#jeide" class="menu__link">Jeans</a>
        </li>

        <li class="menu__item">
            <a href="#burj" class="menu__link">Shalbar</a>
        </li>

        <li class="menu__item">
            <a href="{% url 'bastama:category_products' 'jeide' %}" class="menu__link"><span style="color: yellow;">Jeide</span> </a>
        </li>
        <li class="menu__item">
            <a href="{% url 'bastama:category_products' 'qosymsha' %}" class="menu__link"><span style="color: yellow;">Qosymsha</span> </a>
        </li>
        <li class="menu__item">
            <a href="{% url 'bastama:category_products' 'gift' %}" class="menu__link"><span style="color: yellow;">Gift</span> </a>
        </li>
    </ul>
</div>
<!-- --------------------------------------------------------------------------------------- -->
<main>
    <div class="content">
        {% if jeans %}
        <div class="nameblock1" id="jeide">gfvgrd</div>
        <div class="nameblock" id="jeide">#Jeans</div>
        <div class="content_blocks">
            {% for prod in jeans %}
            <div class="cardblock">
                <div class="imageblock15" style="background: url({{ prod.first_photo.url }})"></div>
                <div class="nameelement">{{ prod.name }}</div>
                <div class="coastel">{{ prod.price | floatformat }} KZT</div>
                <a class="button" href="{% url 'bastama:product_detail' prod.slug %}">Shop Now</a>
            </div>
            {% endfor %}
        </div>
        {% endif %}

        {% if shalbars %}
        <div class="nameblock" id="burj">#Shalbar</div>
         <div class="content_blocks">
             {% for prod in shalbars %}
            <div class="cardblock">
                <div class="imageblock15" style="background: url({{ prod.first_photo.url }})"></div>
                <div class="nameelement">{{ prod.name }}</div>
                <div class="coastel">{{ prod.price | floatformat }} KZT</div>
                <a class="button" href="{% url 'bastama:product_detail' prod.slug %}">Shop Now</a>
            </div>
             <p class="price">${{ product.price }}</p>
            {% endfor %}
         </div>
        </div>
        {% endif %}
</main>

{% endblock content %}

qrep/bastama/templates/bastama/jeide.html
{% extends './components/base.html' %}
{% load static %}

{# Configuring the style path #}
{% block style %}
    <link rel="stylesheet" href="{% static 'bastama/css/jeide.css' %}">
{% endblock style %}

{% block content %}
<div class="sidebar" id="sidebar">
    <ul class="sidebar__menu">
        <li class="menu__item">
            <a href="#jeide" class="menu__link">Jeideler</a>
        </li>

        <li class="menu__item">
            <a href="#burj" class="menu__link">Burjeideler</a>
        </li>

        <li class="menu__item">
            <a href="#kenj" class="menu__link">Kenjeideler</a>
        </li>

        <li class="menu__item">
            <a href="{% url 'bastama:category_products' 'jeans' %}" class="menu__link"><span style="color: yellow;">Jeans</span> </a>
        </li>
        <li class="menu__item">
            <a href="{% url 'bastama:category_products' 'qosymsha' %}" class="menu__link"><span style="color: yellow;">Qosymsha</span> </a>
        </li>
        <li class="menu__item">
            <a href="{% url 'bastama:category_products' 'gift' %}" class="menu__link"><span style="color: yellow;">Gift</span> </a>
        </li>
    </ul>
</div>
<!-- --------------------------------------------------------------------------------------- -->
<main>
    <div class="content">

        {% if jeideler %}
        <div class="nameblock1" id="jeide">gfvgrd</div>
        <div class="nameblock" id="jeide">#Jeideler</div>
        <div class="content_blocks">
            {% for jeide in jeideler %}
            <div class="cardblock">
                <div class="imageblock15" style="background: url({{ jeide.first_photo.url }})"></div>
                <div class="nameelement">{{ jeide.name }}</div>
                <div class="coastel">{{ jeide.price | floatformat }} KZT</div>
                <a class="button" href="{% url 'bastama:product_detail' jeide.slug %}">Shop Now</a>
            </div>
            {% endfor %}
        </div>
        {% endif %}

        {% if birjeideler %}
        <div class="nameblock" >#Burjeideler</div>
        <div class="content_blocks">
            {% for jeide in birjeideler %}
            <div class="cardblock">
                <div class="imageblock15" style="background: url({{ jeide.first_photo.url }})"></div>
                <div class="nameelement">{{ jeide.name }}</div>
                <div class="coastel">{{ jeide.price | floatformat }} KZT</div>
                <a class="button" href="{% url 'bastama:product_detail' jeide.slug %}">Shop Now</a>
            </div>
            {% endfor %}
        </div>
        {% endif %}


        {% if kenjeideler %}
        <div class="nameblock" >#Kenjeide</div>
            <div class="content_blocks">
                {% for jeide in kenjeideler %}
                <div class="cardblock">
                    <div class="imageblock15" style="background: url({{ jeide.first_photo.url }})"></div>
                    <div class="nameelement">{{ jeide.name }}</div>
                    <div class="coastel">{{ jeide.price | floatformat }} KZT</div>
                    <a class="button" href="{% url 'bastama:product_detail' jeide.slug %}">Shop Now</a>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}

</main>
<!-- ------------------------------------------------------------------------------------ -->
{% endblock content %}

qrep/bastama/templates/bastama/qosymsha.html
{% extends './components/base.html' %}
{% load static %}

{# Configuring the style path #}
{% block style %}
    <link rel="stylesheet" href="{% static 'bastama/css/qosymsha.css' %}">
{% endblock style %}

{# Block Content starting here #}
{% block content %}
<div class="sidebar" id="sidebar">
    <ul class="sidebar__menu">
        <li class="menu__item">
            <a href="#jeide" class="menu__link">Sömke</a>
        </li>

        <li class="menu__item">
            <a href="#kepka" class="menu__link">Kepka</a>
        </li>

        <li class="menu__item">
            <a href="#panama" class="menu__link">Panama</a>
        </li>

         <li class="menu__item">
            <a href="#qalpaq" class="menu__link">Qalpaq</a>
        </li>

        <li class="menu__item">
            <a href="#kese" class="menu__link">Kese</a>
        </li>

        <li class="menu__item">
            <a href="#botelke" class="menu__link">Bötelke</a>
        </li>

        <li class="menu__item">
            <a href="#betperde" class="menu__link">Betperde</a>
        </li>

        <li class="menu__item">
            <a href="{% url 'bastama:category_products' 'jeans' %}" class="menu__link"><span style="color: yellow;">Jeans</span> </a>
        </li>

        <li class="menu__item">
            <a href="{% url 'bastama:category_products' 'jeide' %}" class="menu__link"><span style="color: yellow;">Jeide</span> </a>
        </li>

        <li class="menu__item">
            <a href="{% url 'bastama:category_products' 'gift' %}" class="menu__link"><span style="color: yellow;">Gift</span> </a>
        </li>
    </ul>
</div>
<!-- --------------------------------------------------------------------------------------- -->
<main>
    <div class="content">
        {% if somkeler %}
        <div class="nameblock1" id="jeide">gfvgrd</div>
        <div class="nameblock" id="jeide">#Sömke</div>
        <div class="content_blocks">
            {% for prod in somkeler %}
                <div class="cardblock">
                    {% if prod.first_photo %}
                        <div class="imageblock15" style="background: url({{ prod.first_photo.url }})"></div>
                    {% else %}
                        <div class="imageblock15">No photo</div>
                    {% endif %}
                    <div class="nameelement">{{ prod.name }}</div>
                    <div class="coastel">{{ prod.price | floatformat }} KZT</div>
                    <a class="button" href="{% url 'bastama:product_detail' prod.slug %}">Shop Now</a>
                </div>
            {% endfor %}
        </div>
        {% endif %}

        {% if kepkalar %}
        <div class="nameblock" id="kepka">#Kepka</div>
        <div class="content_blocks">
            {% for prod in kepkalar %}
                <div class="cardblock">
                   {% if prod.first_photo %}
                        <div class="imageblock15" style="background: url({{ prod.first_photo.url }})"></div>
                    {% else %}
                        <div class="imageblock15">No photo</div>
                    {% endif %}
                    <div class="nameelement">{{ prod.name }}</div>
                    <div class="coastel">{{ prod.price | floatformat }} KZT</div>
                    <a class="button" href="{% url 'bastama:product_detail' prod.slug %}">Shop Now</a>
                </div>
            {% endfor %}
        </div>
        {% endif %}

        {% if panamalar %}
        <div class="nameblock" id="panama">#Panama</div>
        <div class="content_blocks">
            {% for prod in panamalar %}
                <div class="cardblock">
                    {% if prod.first_photo %}
                        <div class="imageblock15" style="background: url({{ prod.first_photo.url }})"></div>
                    {% else %}
                        <div class="imageblock15">No photo</div>
                    {% endif %}
                    <div class="nameelement">{{ prod.name }}</div>
                    <div class="coastel">{{ prod.price | floatformat }} KZT</div>
                    <a class="button" href="{% url 'bastama:product_detail' prod.slug %}">Shop Now</a>
                </div>
            {% endfor %}
        </div>
        {% endif %}

        {% if qalpaktar %}
        <div class="nameblock" id="qalpaq">#Qalpaq</div>
        <div class="content_blocks">
            {% for prod in qalpaktar %}
                <div class="cardblock">
                    {% if prod.first_photo %}
                        <div class="imageblock15" style="background: url({{ prod.first_photo.url }})"></div>
                    {% else %}
                        <div class="imageblock15">No photo</div>
                    {% endif %}
                    <div class="nameelement">{{ prod.name }}</div>
                    <div class="coastel">{{ prod.price | floatformat }} KZT</div>
                    <a class="button" href="{% url 'bastama:product_detail' prod.slug %}">Shop Now</a>
                </div>
            {% endfor %}
        </div>
        {% endif %}

        {% if keseler %}
        <div class="nameblock" id="kese" >#Kese</div>
        <div class="content_blocks">
            {% for prod in keseler %}
                <div class="cardblock">
                    {% if prod.first_photo %}
                        <div class="imageblock15" style="background: url({{ prod.first_photo.url }})"></div>
                    {% else %}
                        <div class="imageblock15">No photo</div>
                    {% endif %}
                    <div class="nameelement">{{ prod.name }}</div>
                    <div class="coastel">{{ prod.price | floatformat }} KZT</div>
                    <a class="button" href="{% url 'bastama:product_detail' prod.slug %}">Shop Now</a>
                </div>
            {% endfor %}
        </div>
        {% endif %}

        {% if botelkeler %}
        <div class="nameblock" id="botelke">#Bötelke</div>
        <div class="content_blocks">
            {% for prod in botelkeler %}
                <div class="cardblock">
                    {% if prod.first_photo %}
                        <div class="imageblock15" style="background: url({{ prod.first_photo.url }})"></div>
                    {% else %}
                        <div class="imageblock15">No photo</div>
                    {% endif %}
                    <div class="nameelement">{{ prod.name }}</div>
                    <div class="coastel">{{ prod.price | floatformat }} KZT</div>
                    <a class="button" href="{% url 'bastama:product_detail' prod.slug %}">Shop Now</a>
                </div>
            {% endfor %}
        </div>
        {% endif %}

        {% if betperdeler %}
        <div class="nameblock" id="betperde">#Betperde</div>
        <div class="content_blocks">
            {% for prod in betperdeler %}
            <div class="cardblock">
                {% if prod.first_photo %}
                    <div class="imageblock15" style="background: url({{ prod.first_photo.url }})"></div>
                {% else %}
                    <div class="imageblock15">No photo</div>
                {% endif %}
                <div class="nameelement">{{ prod.name }}</div>
                <div class="coastel">{{ prod.price | floatformat }} KZT</div>
                <a class="button" href="{% url 'bastama:product_detail' prod.slug %}">Shop Now</a>
            </div>
            {% endfor %}
        </div>
        {% endif %}

    </div>

</main>

<!-- ------------------------------------------------------------------------------------ -->
{% endblock content %}

qrep/bastama/templates/bastama/search.html
{% extends './components/base.html' %}
{% load static %}

{# Configuring the style path #}
{% block style %}
    <link rel="stylesheet" href="{% static 'bastama/css/search.css' %}">
{% endblock style %}

{# Block of Content starting right here #}
{% block content %}
    <div class="content">
        <form method="post">
            {% csrf_token %}
            <input id="search" type="search" name="search" placeholder="Search..." />
            <label id="bt" type="submit">Go</label>
        </form>

        <div class="content_blocks" style="margin-top: 20px">
        {% if products %}
            {% for prod in products %}
            <div class="cardblock">
                {% if prod.first_photo.url %}
                    <div class="imageblock15" style="background: url({{ prod.first_photo.url }})"></div>
                {% else %}
                    <div class="imageblock15" style="background: url({% static 'bastama/images/default/download.jpeg' %})"></div>
                {% endif %}
                <div class="nameelement">{{ prod.name }}</div>
                <div class="coastel">{{ prod.price | floatformat }} KZT</div>
                <a class="button" href="basket.html">Shop Now</a>
            </div>
            {% endfor %}
        {% else %}
            <div class="cardblock">
                <h3>Search something</h3>
            </div>
        {% endif %}
        </div>
        <h1 id="h1"></h1>
    </div>
{% endblock content %}

qrep/bastama/templates/bastama/views/favorite_products.html
{% extends '../components/base.html' %}
{% load static %}

{% block style %}
{% endblock %}

{% block content %}
<main>
    <div class="content">
        {% if favorites %}
            {% for fav in favorites %}
            <div class="cardblock">
                {% if fav.product.first_photo.url %}
                    <div class="imageblock15" style="background: url({{ fav.product.first_photo.url }})"></div>
                {% else %}
                    <div class="imageblock15" style="background: url({% static 'bastama/images/default/download.jpeg' %})"></div>
                {% endif %}
                <div class="nameelement">{{ fav.product.name }}</div>
                <div class="coastel">{{ fav.product.price | floatformat }} KZT</div>
                <a class="button" href="{% url 'bastama:product_detail' fav.product.slug %}">Shop Now</a>
            </div>
            {% endfor %}
        {% else %}
            <h1>You don't have favorites</h1>
        {% endif %}
    </div>
</main>
{% endblock content %}

qrep/bastama/templates/bastama/views/product.html
{% extends '../components/base.html' %}
{% load static %}

{# Configuring the style path #}
{% block style %}
    <link rel="stylesheet" href="{% static 'bastama/css/product.css' %}">
{% endblock style %}

{% block content %}
<main>
    <div class="mainken">
        <div class="kenjeide">
            <img id="prod" src="/media/{{ data.first_photo}}" alt="" width="300px" height="300px">
            <div class="infoabout">
            <div class="texth">
                <h1>{{data.name}}</h1>
            </div>
            <div class="coast">{{ data.price|floatformat }} KZT</div>
            <div class="colours">
                <div class="textcolour">Colour select:</div>
                <div class="buttoncolour">
                    {% for color in data.productattribute_set.all %}
                    <button id="first" onclick="changec(this)" class="butselectcolf" style="background-color:{{color.color.color_code}}"></button>
                    {% endfor%}
                </div>
            </div>
            <div class="aboutsize">
                <div>SIZE:</div>
                <div class="buttonsizes">
                    {% for size in data.productattribute_set.all %}
                    <button class="butselectss">{{size.size}}</button>
                    {% endfor %}
                </div>
            </div>
            <div class="aboutcomposition">
                <div class="comp">COMPOSITION:</div>
                <div>{{data.description}}</div>
            </div>
            <a class="button" href="basket.html">Add to bag</a>
            </div>
        </div>
    </div>
</main>
{% endblock %}