QazaqRepublic/qrep/accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('register/', registerPage, name='register'),
    path('login/', loginPage, name='login'),
    path('logout/', logoutUser, name='logout'),
]

QazaqRepublic/qrep/bastama/urls.py
from django.urls import path
from .views import *

app_name = 'bastama'

urlpatterns = [
    path('', index, name='home'),
    path('category/<str:cat_name>/', category_products, name='category_products'),
    path('product/<slug:slug>/', product_detail, name='product_detail'),

    path('favorite/', favorite_products, name='favorite'),
    path('basket/', basket, name='basket'),
    path('lookbook/', lookbook, name='lookbook'),
    path('search/', search, name='search'),

    path('test/<slug:slug>/', test, name='test'),
    path('update_favs/<slug:slug>/', click_like, name='click_like')
]

QazaqRepublic/qrep/cart/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path(r'^$', views.cart_detail, name='cart_detail'),
    path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

QazaqRepublic/qrep/qrep/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bastama.urls')),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

QazaqRepublic/qrep/bastama/models.py
from django.db import models
from django.contrib.auth.models import User  # Importing User model from auth app


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)

    def __str__(self):
        return self.user.username if self.user else self.name


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'


class Color(models.Model):
    name = models.CharField(max_length=100)
    color_code = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Size(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Product(models.Model):
    slug = models.SlugField(unique=True, max_length=200)
    name = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    first_photo = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Favors(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=True)
    transaction = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def get_basket_amount(self):
        basket_order_items = self.orderitem_set.all()
        return sum([item.quantity * item.product.price for item in basket_order_items])

    @property
    def get_basket_total(self):
        basket_order_items = self.orderitem_set.all()
        return sum([item.quantity for item in basket_order_items])


class OrderItem(models.Model):

    # Cloth size tuples
    XSMALL = 'XS'
    SMALL = 'S'
    MEDIUM = 'M'
    LARGE = 'L'
    XLARGE = 'XL'
    XXLARGE = 'XXL'
    CLOTHES_SIZE = [
        (XSMALL, 'extra small'),
        (SMALL, 'small'),
        (MEDIUM, 'medium'),
        (LARGE, 'large'),
        (XLARGE, 'extra large'),
        (XXLARGE, 'extra extra large'),
    ]

    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    size = models.CharField(choices=CLOTHES_SIZE, default=None, max_length=10)


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=255, null=True)
    city = models.CharField(max_length=255, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address


class ProductAttribute(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    color = models.ForeignKey(Color, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)

    def __str__(self):
        return self.product.name

QazaqRepublic/qrep/bastama/views.py
from django.http import HttpResponse
from django.views.generic import *
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404
from cart.forms import CartAddProductForm

from .models import *
from .utils import *

app_name = 'bastama'


def index(request):
    if request.method == "POST":
        message_email = request.POST['message-email']
        message_name = request.POST['message-name']
        message = request.POST['message']

        send_mail(
            'message from ' + message_name + ',' + message_email,
            message,
            message_email,
            ['200103223@stu.sdu.edu.kz'],
        )
        return redirect("bastama:home")

    else:
        return render(request, 'bastama/index.html', {'title': 'Qazaq Republic'})

    # if request.method == "POST":
    #     message_email = request.GET['message-ems']
    #
    #     send_mail(
    #         'subscription from ' + message_ems,
    #         ['200103223@stu.sdu.edu.kz'],
    #     )
    #     return redirect("bastama:home")
    #
    #
    #   #  return render(request, 'bastama/index.html', {'message_name':message_name},{'title': 'Qazaq Republic'})
    #
    # else: return render(request, 'bastama/index.html', {'title': 'Qazaq Republic'})

def gift(request):
    return render(request, 'bastama/gift.html')

def basket(request):
    basket_data = get_basket_data(request)  # Getting all products from basket
    print(basket_data)
    return render(request, 'bastama/basket.html')


def favorite_products(request):
    products = get_favorite_products(request)
    print(products[0].product.name)
    return HttpResponse('Favorite page')


def search(request):
    context = {
        'title': 'Search'
    }
    if request.method == 'POST':
        context['products'] = Product.objects.filter(name__contains=request.POST['search'], category__name__contains=request.POST['search'])
        print(context['products'])

    return render(request, 'bastama/search.html', context)

def lookbook(request):
    return render(request, 'bastama/lookbook.html')


def category_products(request, cat_name):
    context = {}
    template_url = 'bastama/'
    products_from_subcategory = SIDEBAR_SUBCATEGORY_PRODUCTS[cat_name]

    if cat_name == 'jeans':
        template_url += 'jeans.html'
    elif cat_name == 'jeide':
        template_url += 'jeide.html'
    elif cat_name == 'qosymsha':
        template_url += 'qosymsha.html'
    elif cat_name == 'gift':
        template_url += 'gift.html'

    for product_tupple in products_from_subcategory:
        context_key = product_tupple[0]
        value_to_filter = product_tupple[1]
        context['title'] = value_to_filter
        context[context_key] = Product.objects.filter(category__name=value_to_filter)

    return render(request, template_url, context)


def product_detail(request, slug):
    print(slug)
    product = Product.objects.get(slug=slug)
    print(product)
    return render(request, 'bastama/product.html', {'data': product})


def test(request, slug):
    context = {'title': 'test'}
    product = Product.objects.get(slug=slug)
    print(product)
    context['product'] = product

    return render(request, 'bastama/components/test.html', context)


def click_like(request, slug):
    customer = get_or_create_customer(request.user)
    favorite_product = Product.objects.get(slug=slug)

    favorite, is_fav = is_favorite_of_customer(customer, favorite_product)

    print(favorite)
    print(is_fav)

    if is_fav:
        favorite.delete()
    else:
        Favors.objects.create(customer=customer, product=favorite_product)

    return redirect('bastama:test', slug=slug)



################################################
def product_detail_2(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'bastama/test.html', {'product': product,
                                 'cart_product_form': cart_product_form})
#################################################################3

QazaqRepublic/qrep/bastama/templates/bastama/components/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Podkova:wght@800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Spartan:wght@500&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://unpkg.com/babel-standalone/babel.min.js"></script>
    <script src="https://unpkg.com/vue/dist/vue.min.js"></script>
    <script src="https://unpkg.com/vue-material@beta"></script>

    <link rel="stylesheet" href="{% static 'bastama/css/style.css' %}">
    {% block style %}
    {% endblock  %}
    <title>{{ title }}</title>
</head>
<body>

{% include './header.html' %}

{% block content %}
{% endblock  %}

{% include './footer.html' %}

<script type="text/javascript" src="{% static 'bastama/js/script.js' %}"></script>
</body>
</html>

QazaqRepublic/qrep/bastama/templates/bastama/components/footer.html
<footer class="bg-light text-center text-lg-start footer">
    <!-- Copyright -->
    <div class="text-center p-3 text-light" style="background-color: #0045c0;">
      © 2017 Copyright:
      <a class="text-light" href="{% url 'bastama:home' %}">Qazaq Republic - Design: Dollar Bills</a>
    </div>
    <!-- Copyright -->
</footer>

QazaqRepublic/qrep/bastama/templates/bastama/components/header.html
{% load static %}
<style>
    .hello_msg {
        font-size: 18px;
        color: #fcfaf8;
        margin: 25px 20px;
    }
    .hello-log{
        color: white;
    }
</style>

<header>
    <div class="header_left">
        <button class="homebut">
            <a href="{% url 'bastama:home' %}" title="Home" class="qrsvg"><img class="logo" src="{% static 'bastama/images/default/QR.jpg' %}"></a>
        </button>
        <div class="qazrep">
            <p>QAZAQ REPUBLIC</p>
        </div>
    </div>
    <div class="header_right">
        {% if request.user.is_authenticated %}
        <span class="hello_msg">Welcome, {{request.user}}</span>
        <span class="hello_msg"><a class="hello-log" href="{% url 'accounts:logout' %}">Logout</a></span>
        {% else %}
        <span class="hello_msg"><a class="hello-log" href="{% url 'accounts:login' %}">Login</a></span>
        {% endif %}

        <button class="basketbut">
            <a href="{% url 'bastama:basket' %}" title="basket" class="basketsvg">
                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="white" class="bi bi-cart3" viewBox="0 0 16 16">
                  <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                </svg>
            </a>
        </button>
        <button class="searchbut">
            <a href="{% url 'bastama:search' %}" title="search" class="searchsvg">
            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="white" class="bi bi-search" viewBox="0 0 16 16">
                  <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
            </svg>
            </a>
        </button>
        <form action=""></form>
        <button class="hamburger" onclick="openSide()">
            <span></span>
            <span></span>
            <span></span>
        </button>

    </div>
</header>

QazaqRepublic/qrep/bastama/templates/bastama/components/test.html
{% load static %}

{# Configuring the style path #}
{% block style %}
    <link rel="stylesheet" href="{% static 'bastama/css/fix.css' %}">
    <link rel="stylesheet" href="{% static 'bastama/css/style.css' %}">
{% endblock style %}

{% block content %}
    <main>
        <div class="content">
            <h1>Order page</h1>
            <div class="cardblock">
                <div class="imageblock15" style="background: url({{ product.first_photo.url }})"></div>
                <div class="nameelement">{{ product.name }}</div>
                <div class="coastel">{{ product.price | floatformat }} KZT</div>
                <a class="button" href="#">Order</a>
                <a class="button" href="{% url 'bastama:click_like' product.slug %}">Like</a>
            </div>
        </div>
    </main>
    <script src="{% static 'bastama/js/basket.js' %}"></script>
{% endblock content %}